// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.3
// source: protobuf/contact.proto

package golang_protobuf_contact

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CRUD_Create_FullMethodName  = "/golang_protobuf_contact.CRUD/Create"
	CRUD_GetList_FullMethodName = "/golang_protobuf_contact.CRUD/GetList"
	CRUD_GetOne_FullMethodName  = "/golang_protobuf_contact.CRUD/GetOne"
	CRUD_Update_FullMethodName  = "/golang_protobuf_contact.CRUD/Update"
	CRUD_Delete_FullMethodName  = "/golang_protobuf_contact.CRUD/Delete"
)

// CRUDClient is the client API for CRUD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CRUDClient interface {
	Create(ctx context.Context, in *ProtoContactRepo_ProtoContact, opts ...grpc.CallOption) (*ProtoContactRepo_ProtoContact, error)
	GetList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (CRUD_GetListClient, error)
	GetOne(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*ProtoContactRepo_ProtoContact, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ProtoContactRepo_ProtoContact, error)
	Delete(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
}

type cRUDClient struct {
	cc grpc.ClientConnInterface
}

func NewCRUDClient(cc grpc.ClientConnInterface) CRUDClient {
	return &cRUDClient{cc}
}

func (c *cRUDClient) Create(ctx context.Context, in *ProtoContactRepo_ProtoContact, opts ...grpc.CallOption) (*ProtoContactRepo_ProtoContact, error) {
	out := new(ProtoContactRepo_ProtoContact)
	err := c.cc.Invoke(ctx, CRUD_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDClient) GetList(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (CRUD_GetListClient, error) {
	stream, err := c.cc.NewStream(ctx, &CRUD_ServiceDesc.Streams[0], CRUD_GetList_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &cRUDGetListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CRUD_GetListClient interface {
	Recv() (*ProtoContactRepo_ProtoContact, error)
	grpc.ClientStream
}

type cRUDGetListClient struct {
	grpc.ClientStream
}

func (x *cRUDGetListClient) Recv() (*ProtoContactRepo_ProtoContact, error) {
	m := new(ProtoContactRepo_ProtoContact)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cRUDClient) GetOne(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*ProtoContactRepo_ProtoContact, error) {
	out := new(ProtoContactRepo_ProtoContact)
	err := c.cc.Invoke(ctx, CRUD_GetOne_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*ProtoContactRepo_ProtoContact, error) {
	out := new(ProtoContactRepo_ProtoContact)
	err := c.cc.Invoke(ctx, CRUD_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDClient) Delete(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, CRUD_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRUDServer is the server API for CRUD service.
// All implementations should embed UnimplementedCRUDServer
// for forward compatibility
type CRUDServer interface {
	Create(context.Context, *ProtoContactRepo_ProtoContact) (*ProtoContactRepo_ProtoContact, error)
	GetList(*emptypb.Empty, CRUD_GetListServer) error
	GetOne(context.Context, *wrapperspb.StringValue) (*ProtoContactRepo_ProtoContact, error)
	Update(context.Context, *UpdateRequest) (*ProtoContactRepo_ProtoContact, error)
	Delete(context.Context, *wrapperspb.StringValue) (*wrapperspb.BoolValue, error)
}

// UnimplementedCRUDServer should be embedded to have forward compatible implementations.
type UnimplementedCRUDServer struct {
}

func (UnimplementedCRUDServer) Create(context.Context, *ProtoContactRepo_ProtoContact) (*ProtoContactRepo_ProtoContact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCRUDServer) GetList(*emptypb.Empty, CRUD_GetListServer) error {
	return status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedCRUDServer) GetOne(context.Context, *wrapperspb.StringValue) (*ProtoContactRepo_ProtoContact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedCRUDServer) Update(context.Context, *UpdateRequest) (*ProtoContactRepo_ProtoContact, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCRUDServer) Delete(context.Context, *wrapperspb.StringValue) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

// UnsafeCRUDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CRUDServer will
// result in compilation errors.
type UnsafeCRUDServer interface {
	mustEmbedUnimplementedCRUDServer()
}

func RegisterCRUDServer(s grpc.ServiceRegistrar, srv CRUDServer) {
	s.RegisterService(&CRUD_ServiceDesc, srv)
}

func _CRUD_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtoContactRepo_ProtoContact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRUD_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).Create(ctx, req.(*ProtoContactRepo_ProtoContact))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUD_GetList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CRUDServer).GetList(m, &cRUDGetListServer{stream})
}

type CRUD_GetListServer interface {
	Send(*ProtoContactRepo_ProtoContact) error
	grpc.ServerStream
}

type cRUDGetListServer struct {
	grpc.ServerStream
}

func (x *cRUDGetListServer) Send(m *ProtoContactRepo_ProtoContact) error {
	return x.ServerStream.SendMsg(m)
}

func _CRUD_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRUD_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).GetOne(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUD_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRUD_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUD_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRUD_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).Delete(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

// CRUD_ServiceDesc is the grpc.ServiceDesc for CRUD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CRUD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "golang_protobuf_contact.CRUD",
	HandlerType: (*CRUDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CRUD_Create_Handler,
		},
		{
			MethodName: "GetOne",
			Handler:    _CRUD_GetOne_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CRUD_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CRUD_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetList",
			Handler:       _CRUD_GetList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protobuf/contact.proto",
}
